name: e2e tests iOS

on: [push]

jobs:
  test-ios:
    name: e2e-ios-test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.20.0
      # build App
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v5
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
          working-directory: example/ios
      - name: Install node_modules in root
        run: yarn install --frozen-lockfile
      - name: Install node_modules in example
        run: yarn install --frozen-lockfile --cwd example
      - name: Fix for ruby
        working-directory: example/ios
        run: |
          bundle config --local build.ffi --with-cflags=-Wno-error=implicit-function-declaration
          bundle install
      - name: Install Pods
        working-directory: example/ios
        run: bundle exec pod install --no-repo-update
      - name: Build iOS App
        working-directory: example
        # run: yarn run react-native run-ios --configuration Release --simulator "iPhone 13 (15.2)"
        run: yarn run react-native run-ios --mode Release
      # Install Maestro
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
      - name: Add Maestro to path
        run: echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      # Run e2e test
      - name: Test
        run: maestro test e2e-tests/maestro-flow-ios.yml

      # - name: Debug
      #   if: always()
      #   run: maestro hierarchy
